# Generated by Django 5.0.4 on 2024-04-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('customer', 'customer'), ('loan_representative', 'loan representative'), ('operational_head', 'operational_head'), ('loan_sanctioning_officer', 'loan_sanctioning_officer'), ('admin', 'admin'), ('account_head', 'account_head')], max_length=24, null=True),
        ),
    ]
